### PR TITLE
Fix data types

### PR DESCRIPTION
**Pull request by Vaggelis1994**
Removed the following typedefs, in order to make the data type declaration more explicit:  
`IntegetT` and `FloatT` completely removed.  Moreover, `Integer` and `Float` were replaced respectively by `mpz_t` and `mpfr_t`.
The default class type for `Z_NR<>` is set to `mpz_t` and `FP_NR<>` is set to `mpfr_t`. Hence, the instances of `Z_NR<mpz_t>` were replaced by `Z_NR<>` and `FP_NR<mpfr_t>` by `FP_NR<>`.
All instances of `IntVect` were replaced by `vector<Z_NR<>>`  and all instances of `FloatVect` were replaced by `vector<FP_NR<>>`.
Finally, `IntMatrix` is everywhere replaced from `ZZ_mat<mpz_t>` and `FloatMatrix` is everywhere replaced from `FP_mat<mpfr_t>`.

### CODE REVIEW

**Comment by shi-bai** [comment]
Since this changes the interface, I suggest this pull request to be merged some time later next week

1) it might be good to keep the IntegetT and FloatT for a 2 weeks (completely remove them might break other's code in pull request/branchs). In this pull request, we can just change the style (e.g. from Integer to  Z_NR<mpz_t>).
2) later, for any re-occurrences of IntegetT and FloatT in future pull requests, we do a "sed" replace. 
3)  we are trying to make things more explicit, why not using Z_NR<mpz_t> explicitly instead Z_NR<> (and FP_NR). --> open for discussion.

**Comment by lducas** [comment]
Would it be a good time to proceed with this one ?

**Comment by shi-bai** [comment]
there are some things to fix for the tests. It seems that I don't have permission to edit Vaggelis1994's branch. Just created a new local branch for that.

**Comment by Vaggelis1994** [comment]
Hi,
Can I give you permission somehow?

**Comment by shi-bai** [comment]
Yes, but there seems to be an easier way: I just uploaded a new branch updated-fix_data_types. You may just merge that branch with your fix_data_types branch and then push to remote again. This will update your pull request.

**Comment by Vaggelis1994** [comment]
I see. It's fine with me if you commit your branch instead, directly. I suggest that since mine was of older version, too.

**Comment by shi-bai** [comment]
OK, let me close this as I merged the other one.

**Pull request merged**
