### PR TITLE
Fix #474 -- remove redundant template parameters

### LINKED ISSUE #474: Code cannot be compile when using c++20.
In my work, I wish to use the latest c++ compiler. However, the compiling can't be done with gcc-11.
It seems like the following code
```c++
template <class Z = mpz_t> class Z_NR
{

  Z data;

public:
  /**
   * Constructors.
   */
  inline Z_NR<Z>();
  inline Z_NR<Z>(const Z_NR<Z> &z);
  inline Z_NR<Z>(const Z &z);
  inline ~Z_NR<Z>();

// other codes are omitted.
};
```
cannot be compiled. g++ says
```g++
/usr/local/include/fplll/nr/nr_Z.inl:30:10: error: template-id not allowed for destructor
   30 |   inline ~Z_NR<Z>();
      |          ^
```

There are other errors (all about tempate):
```g++
/usr/local/include/fplll/nr/nr_Z_d.inl:17:20: error: template-id ‘__dt <>’ for ‘fplll::Z_NR<double>::~Z_NR()’ does not match any template declaration
   17 | template <> inline Z_NR<double>::~Z_NR() {}
      |                    ^~~~~~~~~~~~


/usr/local/include/fplll/nr/nr_Z.inl:18:34: note: candidate is: ‘constexpr fplll::Z_NR<double>::~Z_NR()’
   18 | template <class Z = mpz_t> class Z_NR
      |                                  ^~~~

/usr/local/include/fplll/nr/nr_Z_l.inl:17:20: error: template-id ‘__dt <>’ for ‘fplll::Z_NR<long int>::~Z_NR()’ does not match any template declaration
   17 | template <> inline Z_NR<long>::~Z_NR() {}
      |                    ^~~~~~~~~~

/usr/local/include/fplll/nr/nr_Z.inl:18:34: note: candidate is: ‘constexpr fplll::Z_NR<long int>::~Z_NR()’
   18 | template <class Z = mpz_t> class Z_NR
      |                                  ^~~~


/usr/local/include/fplll/nr/nr_Z_mpz.inl:17:20: error: template-id ‘__dt <>’ for ‘fplll::Z_NR<__mpz_struct [1]>::~Z_NR()’ does not match any template declaration
   17 | template <> inline Z_NR<mpz_t>::~Z_NR() { mpz_clear(data); }
      |                    ^~~~~~~~~~~

/usr/local/include/fplll/nr/nr_Z.inl:18:34: note: candidate is: ‘constexpr fplll::Z_NR<__mpz_struct [1]>::~Z_NR()’
   18 | template <class Z = mpz_t> class Z_NR
      |                                  ^~~~

/usr/local/include/fplll/nr/nr_FP.inl:32:10: error: template-id not allowed for destructor
   32 |   inline ~FP_NR<F>();
      |          ^

/usr/local/include/fplll/nr/nr_FP_d.inl:20:20: error: template-id ‘__dt <>’ for ‘fplll::FP_NR<double>::~FP_NR()’ does not match any template declaration
   20 | template <> inline FP_NR<double>::~FP_NR() {}
      |                    ^~~~~~~~~~~~~

/usr/local/include/fplll/nr/nr_FP.inl:21:35: note: candidate is: ‘constexpr fplll::FP_NR<double>::~FP_NR()’
   21 | template <class F = mpfr_t> class FP_NR
      |                                   ^~~~~

/usr/local/include/fplll/nr/nr_FP_ld.inl:21:20: error: template-id ‘__dt <>’ for ‘fplll::FP_NR<long double>::~FP_NR(
’ does not match any template declaration
   21 | template <> inline FP_NR<long double>::~FP_NR() {}
      |                    ^~~~~~~~~~~~~~~~~~

/usr/local/include/fplll/nr/nr_FP.inl:21:35: note: candidate is: ‘constexpr fplll::FP_NR<long double>::~FP_NR()’
   21 | template <class F = mpfr_t> class FP_NR
      |                                   ^~~~~

/usr/local/include/fplll/nr/nr_FP_dpe.inl:22:20: error: template-id ‘__dt <>’ for ‘fplll::FP_NR<dpe_struct [1]>::~FP_NR()’ does not match any template declaration
   22 | template <> inline FP_NR<dpe_t>::~FP_NR() { dpe_clear(data); }
      |                    ^~~~~~~~~~~~

/usr/local/include/fplll/nr/nr_FP.inl:21:35: note: candidate is: ‘constexpr fplll::FP_NR<dpe_struct [1]>::~FP_NR()’
   21 | template <class F = mpfr_t> class FP_NR
      |                                   ^~~~~

/usr/local/include/fplll/nr/nr_FP_mpfr.inl:20:20: error: template-id ‘__dt <>’ for ‘fplll::FP_NR<__mpfr_struct [1]>::~FP_NR()’ does not match any template declaration
   20 | template <> inline FP_NR<mpfr_t>::~FP_NR() { mpfr_clear(data); }
      |                    ^~~~~~~~~~~~~

/usr/local/include/fplll/nr/nr_FP.inl:21:35: note: candidate is: ‘constexpr fplll::FP_NR<__mpfr_struct [1]>::~FP_NR()’   21 | template <class F = mpfr_t> class FP_NR
      |                                   ^~~~~
```

The code can still be compiled with clang-12. But might still been not working someday.

Would you please let me know whether you are going to fix this?

### PR DESCRIPTION
**Pull request by joerowell**
# What's the problem?

C++20 appears to have outlawed something that fplll had before: redundant typenames in destructors. In particular, the following isn't legal anymore:

```
template<typename F>
class F_Wrapper {
      ~F_Wrapper<F>();
};
```

The standard justifies this as fixing the defects identified in [CWG2237](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#2237)

# What's the fix?
Just remove the template parameters; they weren't ever necessary.

### CODE REVIEW

**Comment by malb** [comment]
There's some extra stuff in this PR but that's perhaps fine?

**Comment by malb** [comment]
Should we add compiling with C++20 to the CI?

**Comment by joerowell** [comment]
That's all old stuff from when I did #470 in #473 . No idea why it's included in this -- maybe I forgot to ``git pull`` or similar before branching? I can close this + re-open with a clean branch if it's an issue.

**Comment by joerowell** [comment]
> Should we add compiling with C++20 to the CI?

So I tried to do this via changing the autotools files (i.e by changing AX_CXX_COMPILE_STDCXX) but ended up with some errors that I couldn't quite diagnose. Personal opinion: C++20 is a bit too bleeding edge right now (i.e modules aren't yet fully supported, etc etc). I'd recommend we hold off for a bit, especially as fplll is still very much a C++11 library. Happy to be persuaded though.

**Pull request merged**
