### PR TITLE
Adding silent rules for automake to get a nicer makefile

### PR DESCRIPTION
**Pull request by tlepoint**
I think having a silent makefile is nicer :-)

The previous behavior can be obtained using `make V=1`

### CODE REVIEW

**Comment by malb** [comment]
I prefer it, too.  Maybe adding a quick comment about `make V=1` to `CONTRIBUTING.md` would be good, though?

**Comment by tlepoint** [comment]
I added a sentence, but I let you change it if you want.

**Comment by malb** [comment]
Looks good, I'll let it hang here for a few days until I merge: this is a "colour of the bike shed" kind of PR, so let's allow everyone to put forward their favourite colour.

**Comment by tlepoint** [comment]
If the developers are uncomfortable with it, another option could also be to only have the silent rules for the release (similarly to the fact that autogen is removed).

**Comment by shi-bai** [comment]
No problem for me. I am happy with cleaner outputs.

  CXX      fplll.lo
  CXX      util.lo
  CXX      lll.lo
  CXX      wrapper.lo
  CXX      bkz.lo
  CXX      bkz_param.lo
  CXX      gso.lo
  CXX      pruner.lo
  CXX      main.o
  CXX      latticegen.o
  CXX      sieve/sieve_main.o
  CXX      enum/topenum.lo
  CXX      enum/enumerate.lo
  CXX      enum/enumerate_base.lo
  CXX      enum/evaluator.lo
  CXX      sieve/sieve_gauss.lo
  CXX      sieve/sieve_gauss_2sieve.lo
  CXX      sieve/sieve_gauss_3sieve.lo
  CXX      sieve/sieve_gauss_4sieve.lo
  CXX      sieve/sampler_basic.lo
  CXXLD    libfplll.la
  CXXLD    latsieve
  CXXLD    fplll
  CXXLD    latticegen

**Pull request merged**
