### PR TITLE
Removed some unneeded comments with code snippets

### PR DESCRIPTION
**Pull request by kodebro**
No significant changes; I removed some unneeded comments (in `gso_gram.*`, `gso.*` and `gso_interface.*`), and also made the code somewhat clearer.

### CODE REVIEW

**Comment by malb** [comment]
Sorry, this conflicts with #256. I merged #256 first since it also fixes Travis on OSX

**Comment by kodebro** [comment]
Ah, okay. As far as I can see, in the conflicts only the way of throwing an error is changed:
`throw std::runtime_error("Error: gptr is equal to the nullpointer.");`
I'll resolve this.

**Comment by kodebro** [comment]
Travis seems to have troubles on Linux, due to a hash sum mismatch (?).

**Comment by shi-bai** [comment]
I saw it's on the https://github.com/travis-ci/travis-ci/issues. 
I checked the pull request and style. It looks good to me. I merge it now; and leave the travis fix for a future pull request (as I guess it's an independent issue).

**Pull request merged**
