### PR TITLE
Two typos and a leaking pkgconfig file

### PR DESCRIPTION
**Pull request by SnarkBoojum**
Those two commits do what is described in the title.

Thanks,

### CODE REVIEW

**Comment by malb** [comment]
Looks good, thanks. Let us know if you need a new point release for packaging (I don't want to proactively create too many of them)

**Comment by SnarkBoojum** [comment]
I don't **require** a point release, but it would be much cleaner. Thanks!

**Comment by malb** [comment]
Okay, maybe let's wait for a week or so to see if there are more issues that should be addressed for packaging etc.

**Comment by SnarkBoojum** [comment]
I have pushed a 5.0.1 package to the experimental part of Debian, so when projects using fplll will have new versions supporting the new fplll, their packager will have an easier time.

If you publish new sub-releases, I'll see them and push them likewise into experimental.

Thanks!

**Pull request merged**
