### PR TITLE
Extenum documentation

### PR DESCRIPTION
**Pull request by joerowell**
Added some documentation to enumerate_ext.h and enumerate_ext.cpp (plus some non-breaking changes to the code for cleanliness). It's probably a good idea to add some const correctness too - will try and do this when I have more time.

### CODE REVIEW

**Comment by cr-marcstevens** [comment]
make check-style ;)

**Comment by cr-marcstevens** [comment]
Why are `tests/*.log` log files added?

**Comment by joerowell** [comment]
Good point!

**Comment by cr-marcstevens** [comment]
Joe: I suggest removing the last 2 commits altogether:
```
   git reset --hard HEAD~2  # remove last 2 commits locally
   git push --force         # force push to remote, removing them on github
```

And `make check-style` still fails, have you installed `clang-format`?

**Pull request merged**
