### PR TITLE
Make Babai test more robust for PPC etc.

### PR DESCRIPTION
**Pull request by joerowell**
Turns out I missed the case for ```long double``` being synonymous with ```__float128``` and a handful of other cases. This PR should finish #500.

### CODE REVIEW

**Comment by joerowell** [comment]
@malb Should we also try the commented out tests for QD? 034e8cb might make those tests more reliable too.

**Comment by malb** [comment]
Oh, cool, yes that'd be great.

typed with thumbs, please excuse my brevity

**Comment by joerowell** [comment]
Sadly it doesn't fix the QD tests: we can fix that in a later PR?

**Comment by malb** [comment]
Yeah, let's leave that for another time!

**Pull request merged**
