### PR TITLE
minimal change to compile with gcc-11

### PR DESCRIPTION
**Pull request by kiwifb**
This PR is to fix issue #462.

### CODE REVIEW

**Comment by malb** [comment]
Thanks!

**Comment by mkoeppe** [comment]
Can we get a new release with this fix?

**Comment by malb** [comment]
Will do. Hopefully this week.

**Comment by malb** [comment]
- https://github.com/fplll/fplll/releases/tag/5.4.1
- https://github.com/fplll/fpylll/releases/tag/0.5.6 (optional)

**Pull request merged**
