### PR TITLE
Set a default external enumeration library

### PR DESCRIPTION
**Pull request by cr-marcstevens**
This PR makes it possible to directly integrate any external enumeration into fplll and be used by default by fplll.

### CODE REVIEW

**Comment by malb** [comment]
Looks good to me, so once the checkstyle issue is fixed, happy to merge.

**Comment by cr-marcstevens** [comment]
Thanks, but indeed all checks failed, so have to fix style and maybe other things.

**Comment by cr-marcstevens** [comment]
BTW this pull request moves the extenum API from the fplll namespace to the main namespace `::`.
This is because the header file doesn't use any other fplll header files, so that it can be copied to extenum libraries without dependencies.

What are your thoughts on this:
1. Should this be moved back to fplll? 
1a. If yes, do we use macros then or just hardcoded `fplll` as namespace?

**Comment by malb** [comment]
TBH, I don't have a strong opinion either way. What's the risk of name collision in some bigger project, i.e. should it be in some namespace?

**Comment by cr-marcstevens** [comment]
@malb do you want to push the green button?

**Comment by malb** [comment]
With pleasure.

**Pull request merged**
